# Generated by Django 4.0.2 on 2022-02-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_text_en'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
